# データの読み込み

- 現状では、ベースにした森先生の資料の丸写しです
- GW明けまでに完成させるので、外に出さないでください
- 森先生の以下の動画を参考にしてください
- GW明けまでに全ての練習問題のコードをひとつのRスクリプトに書いて提出

<iframe width="560" height="315" src="https://www.youtube.com/embed/FugazO_rL7c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

データ分析のためには、データをRStudioにインポート（読み込み）させなければなりません。インポートの方法は、持っているデータのファイル形式によって変わります。

## インポートの準備

インポートしたいファイルは、プロジェクトと同じフォルダに入れておきましょう。 プロジェクトはChapter 2で学習しています。

インポートしたいファイルの形式も確認しておきましょう。 代表的な形式として、CSVファイル（.csv）、Excelファイル（.xlsx, .xls）があります。 拡張子が表示されていない場合はこちらを参考に表示させるようにしましょう。

インポートの前に、ファイルの1行目は変数名（英語）にしておきましょう。

## ファイル形式別のインポート方法

### CSVファイルの場合（.csv）

CSVファイルの場合は、`read.csv`を用います。ファイルの名前がsotsuron.csvの場合、以下のように実行します。

```{r eval=FALSE}
data_original <- read.csv("sotsuron.csv")
```

これは、csvファイルの内容をdata_originalというオブジェクトに格納しています。 オブジェクト名は自由につけることができますが、わかりやすいものにしましょう。 ここでは、インポートした元データであることを明示するため、data_originalという名前にしています。

**練習問題**  
  
- 以下から「tidy_data.csv」をダウンロード
https://www.dropbox.com/s/wm46esg4dicye8j/tidy_data.csv?dl=0  
- `read.csv`を使って読み込み、dataというオブジェクトに格納


## インポートしたデータの確認

上の練習問題のデータがきちんとインポートされたかどうか、確認しておきましょう。

右上のペーンの“Environment”に新しいオブジェクトができているか確認（上の例ではdata）
クリックして左上のペーンに出てくるか確認
`head(data)`で先頭のデータを確認
`str(data)`で各変数の「型」（後で説明）を確認


